---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 25.10.2024 23:28
---


function InitTrig_ESC()
    gg_trg_ESC = CreateTrigger()
    TriggerRegisterPlayerEventEndCinematic(gg_trg_ESC, Player(0))
    TriggerAddAction(gg_trg_ESC, function()
        local pid=GetPlayerId(GetTriggerUnit())
        HealRandomUnitForPlayer(2,10,pid)
    end)
end