---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 26.10.2024 9:22
---
function FindRandomUnitsMax(pid,max)
    local rg=FindAllUnitsForPlayerID(pid)
    local tpmTable={}
    local k=0
    rg=ShuffleTable(rg)
    for i=1,#rg do
        if not IsUnitType(rg[i],UNIT_TYPE_STRUCTURE) and k<max then
            table.insert(tpmTable,rg[i])
            k=k+1
        end
    end
    return tpmTable
end