---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 25.10.2024 21:06
---
function FindAllUnitsForPlayerID(pid)
    local unit=nil
    local e=nil
    local k=0
    --print("ищем")
    local rg={}
    GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
    while true do
        e = FirstOfGroup(perebor)

        if e == nil then break end
        if UnitAlive(e) and GetOwningPlayer(e)==Player(pid) then
            k=k+1
            rg[k]=e
            unit=e
        end
        GroupRemoveUnit(perebor,e)
    end
    return rg
end

function FindUnitOfType(id,flag,x,y)
    --flag nil - вся карта
    --flag any - радиус
    local unit=nil
    local e=nil
    local k=0
    --print("ищем")
    local rg={}
    if not flag then
        GroupEnumUnitsInRect(perebor,bj_mapInitialPlayableArea,nil)
        while true do
            e = FirstOfGroup(perebor)

            if e == nil then break end
            if UnitAlive(e) and GetUnitTypeId(e)==id then
                k=k+1
                rg[k]=e
                unit=e
            end
            GroupRemoveUnit(perebor,e)
        end
    else
        GroupEnumUnitsInRange(perebor,x,y,flag,nil)
        while true do
            e = FirstOfGroup(perebor)

            if e == nil then break end
            if UnitAlive(e) and GetUnitTypeId(e)==id then
                k=k+1
                rg[k]=e
                unit=e
            end
            GroupRemoveUnit(perebor,e)
        end
    end


    if k>1 then
        --	print("Ошибка получено "..k.." юнитов")
    end
    if k>2 then
        unit=rg[GetRandomInt(1,#rg)]
    end
    if unit==nil then
        --	print("Не найдено живых юнитов данного типа")
    end
    return unit,k,rg
end
