---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 2:20
---
function CreateOSKEY_1Actions()
    -----------------------------------------------------------------OSKEY_1
    local gg_trg_EventUpOSKEY_1 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpOSKEY_1, Player(i), OSKEY_1, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpOSKEY_1, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseOSKEY_1 then
            data.ReleaseOSKEY_1 = true
            if DialogTalonActive then
                DialogTalonActive=false
                --print("нажал OSKEY_1",TalonInSlot[1].name)
                BlzFrameSetVisible(DialogMainWindow,false)
                LearnTalonByName(TalonInSlot[1].name,TalonInSlot[1].talon,pid)
                TalonInSlot={}
            end
        end
    end)

    local TrigDepressOSKEY_1 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressOSKEY_1, Player(i), OSKEY_1, 0, false)
    end
    TriggerAddAction(TrigDepressOSKEY_1, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseOSKEY_1 = false
    end)
end

function CreateOSKEY_2Actions()
    -----------------------------------------------------------------OSKEY_2
    local gg_trg_EventUpOSKEY_2 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpOSKEY_2, Player(i), OSKEY_2, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpOSKEY_2, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseOSKEY_2 then
            data.ReleaseOSKEY_2 = true
            if DialogTalonActive then
                if TalonInSlot[2] then
                    DialogTalonActive=false
                    --print("нажал OSKEY_2",TalonInSlot[2].name)
                    LearnTalonByName(TalonInSlot[2].name,TalonInSlot[2].talon,pid)
                    BlzFrameSetVisible(DialogMainWindow,false)
                    TalonInSlot={}
                else
                    print("таланта с таким номером у вас нет в пуле на экране")
                end
            end
        end
    end)

    local TrigDepressOSKEY_2 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressOSKEY_2, Player(i), OSKEY_2, 0, false)
    end
    TriggerAddAction(TrigDepressOSKEY_2, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseOSKEY_2 = false
    end)
end

function CreateOSKEY_3Actions()
    -----------------------------------------------------------------OSKEY_3
    local gg_trg_EventUpOSKEY_3 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpOSKEY_3, Player(i), OSKEY_3, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpOSKEY_3, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseOSKEY_3 then
            data.ReleaseOSKEY_3 = true
            if DialogTalonActive then
                if TalonInSlot[3] then
                    DialogTalonActive=false
                    --print("нажал OSKEY_3",TalonInSlot[3].name)
                    LearnTalonByName(TalonInSlot[3].name,TalonInSlot[3].talon,pid)
                    BlzFrameSetVisible(DialogMainWindow,false)
                    TalonInSlot={}
                else
                    print("таланта с таким номером у вас нет в пуле на экране")
                end
            end
        end
    end)

    local TrigDepressOSKEY_3 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressOSKEY_3, Player(i), OSKEY_3, 0, false)
    end
    TriggerAddAction(TrigDepressOSKEY_3, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseOSKEY_3 = false
    end)
end

function CreateOSKEY_4Actions()
    -----------------------------------------------------------------OSKEY_4
    local gg_trg_EventUpOSKEY_4 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpOSKEY_4, Player(i), OSKEY_4, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpOSKEY_4, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseOSKEY_4 then
            data.ReleaseOSKEY_4 = true
            if DialogTalonActive then
                if TalonInSlot[4] then
                    DialogTalonActive=false
                    --print("нажал OSKEY_3",TalonInSlot[3].name)
                    LearnTalonByName(TalonInSlot[4].name,TalonInSlot[4].talon,pid)
                    BlzFrameSetVisible(DialogMainWindow,false)
                    TalonInSlot={}
                else
                    print("таланта с таким номером у вас нет в пуле на экране")
                end
            end
        end
    end)

    local TrigDepressOSKEY_4 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressOSKEY_4, Player(i), OSKEY_4, 0, false)
    end
    TriggerAddAction(TrigDepressOSKEY_4, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseOSKEY_4 = false
    end)
end
function CreateOSKEY_5Actions()
    -----------------------------------------------------------------OSKEY_5
    local gg_trg_EventUpOSKEY_5 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(gg_trg_EventUpOSKEY_5, Player(i), OSKEY_5, 0, true)
    end
    TriggerAddAction(gg_trg_EventUpOSKEY_5, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        if not data.ReleaseOSKEY_5 then
            data.ReleaseOSKEY_5 = true
            if DialogTalonActive then
                if TalonInSlot[5] then
                    DialogTalonActive=false
                    LearnTalonByName(TalonInSlot[3].name,TalonInSlot[5].talon,pid)
                    BlzFrameSetVisible(DialogMainWindow,false)
                    TalonInSlot={}
                else
                    print("таланта с таким номером у вас нет в пуле на экране")
                end
            end
        end
    end)

    local TrigDepressOSKEY_5 = CreateTrigger()
    for i = 0, bj_MAX_PLAYER_SLOTS - 1 do
        BlzTriggerRegisterPlayerKeyEvent(TrigDepressOSKEY_5, Player(i), OSKEY_5, 0, false)
    end
    TriggerAddAction(TrigDepressOSKEY_5, function()
        local pid = GetPlayerId(GetTriggerPlayer())
        local data = HERO[pid]
        data.ReleaseOSKEY_5 = false
    end)
end