---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 12:16
---
function InitTalonBD()
    Talons = {
        [1] = {
            name = "Полезная благодать",
            icon = "ReplaceableTextures\\CommandButtons\\BTNHolyBolt.blp",
            description = "Исцеляет до 10 случайных союзных живых юнитов с наименьшим ХП на DS единиц здоровья",
            level = 0,
            DS = { 100, 200, 300, 400, 500 },
            pos = 1,
        },
        [2] = {
            name = "Вредная благодать",
            icon = "ReplaceableTextures\\CommandButtons\\BTNHolyBolt.blp",
            description = "Наносит DS едниц урона всей враждебной нежити",
            level = 0,
            DS = { 300, 600, 1000 },
            pos = 2,
        },
        [3] = {
            name = "Доспехи истины",
            icon = "ReplaceableTextures\\CommandButtons\\BTNDevotion.blp",
            description = "Увеличивает броню текущих союзных существ на DS до конца игры",
            level = 0,
            DS = { 5, 10, 15, 20, 25, 30 },
        },
        [4] = {
            name = "Массовая божественность",
            icon = "ReplaceableTextures\\CommandButtons\\BTNDivineIntervention.blp",
            description = "Делает 20 ваших случайных боевых единиц неуязвимыми на DS сек",
            level = 0,
            DS = { 40, 60, 80 },
        },
        [5] = {
            name = "Неуязвимость вечности",
            icon = "ReplaceableTextures\\CommandButtons\\BTNGreaterInvulneralbility.blp",
            description = "Делает DS вашу случайную боевую единицу неуязвимой до конца игры",
            level = 0,
            DS = { 1 },
        },
        [6] = {
            name = "Призыв инженеров",
            icon = "ReplaceableTextures\\CommandButtons\\BTNPeasant.blp",
            description = "Призывает DS рабочих альянса к случайному главному зданию",
            level = 0,
            DS = { 5, 10, 15 },
        },
        [7] = {
            name = "Ремонт и материалы",
            icon = "ReplaceableTextures\\CommandButtons\\BTNRepairOn.blp",
            description = "Ремонтирует все ваши союзные постройки и технику, а так же даёт +DS древесины за каждое целое здание",
            level = 0,
            DS = { 5, 10, 15, 20, 25 },
        },
        [8] = {
            name = "Фальшивые чертежи",
            icon = "ReplaceableTextures\\CommandButtons\\BTNSnazzyScroll.blp",
            description = "DS случайных вражеских зданий потеряет 99%% здоровья",
            level = 0,
            DS = { 3, 6, 9, 12, 50 },
        },
        [9] = {
            name = "Простой инком",
            icon = "ReplaceableTextures\\CommandButtons\\BTNChestOfGold.blp",
            description = "Даёт +DS золота в секунду, складывается многократно",
            level = 0,
            DS = { 5,5,5,5,5,5,5,5 },
        },
        [10] = {
            name = "Нет пехоте",
            icon = "ReplaceableTextures\\CommandButtons\\BTNFootman.blp",
            description = "Убивает DS на всей карте",
            level = 0,
            DS = { "всех пехотинцев" },
        },

    }
end