---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 18.02.2023 0:32
---


DialogTalonActive = false
function CreateDialogTalon()
    DialogTalonActive = true

    if not DialogMainWindow then
        DialogMainWindow = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), '', 0)
        CreateOSKEY_1Actions()
        CreateOSKEY_2Actions()
        CreateOSKEY_3Actions()
        TalonInSlot = {}
        TableTalonsFH = {}
        --print("11111111111111")
    end
    BlzFrameSetVisible(DialogMainWindow, true)
    DestroyTalonFH()
    local maxI = GetRandomInt(1, 5)
    local x, y = 0.2, 0.3
    if maxI == 5 then
        x = 0.08
    elseif maxI == 4 then
        x = 0.08 + 0.08
    elseif maxI == 3 then
        x = 0.08 + 0.08 + 0.08
    elseif maxI == 2 then
        x = 0.08 + 0.08 + 0.08 + 0.08
    elseif maxI == 1 then
        x = 0.08 + 0.08 + 0.08 + 0.08 + 0.08
    elseif maxI == 0 then
        print("Создание 0 талантов не допустимо")
        if DialogTalonActive then
            DialogTalonActive = false
            BlzFrameSetVisible(DialogMainWindow, false)
        end
        return
    end

    local tmpTable = TalonReadyForLearn(Talons)
    local stepX = 0.16
    for i = 1, maxI do
        local name, icon, text, level, selfFH = CreateInfoTalonSingle(DialogMainWindow, x + (i - 1) * stepX, y, i)
        SetTalonDescription(tmpTable, i, name, icon, text, level)
        table.insert(TableTalonsFH, selfFH)

    end
end

function TalonReadyForLearn(BD)
    local temptable = {}
    local SHBD = ShuffleTable(BD)

    for i = 1, #SHBD do
        if SHBD[i].level < #(SHBD[i].DS) then
            table.insert(temptable, SHBD[i])
        end
    end
    return temptable
end

function SetTalonDescription(BD, number, name, icon, text, level)
    BlzFrameSetText(name, BD[number].name) -- TODO проверка на пустые таланты
    BlzFrameSetTexture(icon, BD[number].icon, 0, true)
    BlzFrameSetText(text, DSColorDescription(BD[number]))
    BlzFrameSetText(level, ColorText2("[Уровень " .. (BD[number].level + 1) .. "]"))
    TalonInSlot[number] = {
        name = BD[number].name,
        talon = BD[number]
    }

end

function CreateInfoTalonSingle(BoxBarParent, x, y, i)
    local rama = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', BoxBarParent, '', 0)
    BlzFrameSetTexture(rama, "Textures\\Black32", 0, true) --HPElement
    BlzFrameSetSize(rama, 0.15, 0.22)
    BlzFrameSetAbsPoint(rama, FRAMEPOINT_CENTER, x, y)

    local icon = BlzCreateFrameByType('BACKDROP', 'FaceButtonIcon', rama, '', 0)
    BlzFrameSetTexture(icon, "DDSICO\\BrokenHeart", 0, true) --HPElement
    BlzFrameSetSize(icon, 0.08, 0.08)
    BlzFrameSetPoint(icon, FRAMEPOINT_TOP, rama, FRAMEPOINT_TOP, 0, 0)

    local name = BlzCreateFrameByType("TEXT", "ButtonChargesText", rama, "", 0)
    BlzFrameSetPoint(name, FRAMEPOINT_TOP, rama, FRAMEPOINT_TOP, 0.0, -0.08)
    BlzFrameSetText(name, "Название")

    local level = BlzCreateFrameByType("TEXT", "ButtonChargesText", rama, "", 0)
    BlzFrameSetPoint(level, FRAMEPOINT_TOP, rama, FRAMEPOINT_TOP, 0.0, -0.1)
    BlzFrameSetText(level, ColorText2("[Уровень]"))

    local tooltip = BlzCreateFrameByType("FRAME", "TestDialog", rama, "StandardFrameTemplate", 0)
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", tooltip, "", 0)
    BlzFrameSetPoint(tooltip, FRAMEPOINT_CENTER, rama, FRAMEPOINT_CENTER, 0, -0.05)
    BlzFrameSetSize(tooltip, 0.17, 0.125)
    BlzFrameSetSize(text, 0.17, 0.06)
    BlzFrameSetText(text, "Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?,Проверочный текст для фрейма теперь текста больше, а где авто перенос?")
    BlzFrameSetPoint(text, FRAMEPOINT_LEFT, tooltip, FRAMEPOINT_LEFT, 0.02, -0.003)
    BlzFrameSetScale(text, 0.8)

    local press = BlzCreateFrameByType("TEXT", "ButtonChargesText", rama, "", 0)
    BlzFrameSetPoint(press, FRAMEPOINT_CENTER, rama, FRAMEPOINT_CENTER, 0.0, -0.05)
    BlzFrameSetText(press, "Нажмите " .. i)
    BlzFrameSetScale(press, 2)

    return name, icon, text, level, rama
end

function ShuffleTable(tbl)
    for i = #tbl, 2, -1 do
        local j = math.random(i)
        tbl[i], tbl[j] = tbl[j], tbl[i]
        --print(j)
    end
    return tbl
end

function DSColorDescription(talon)
    if #talon.DS > 0 and talon["DS"][talon.level + 1] ~= nil then
        local s = string.gsub(talon.description, "DS", ColorText2(talon["DS"][talon.level + 1]))
        return s
    elseif talon["DS"][talon.level + 1] == nil and #talon.DS > 0 then
        local s = string.gsub(talon.description, "DS", ColorText2(talon["DS"][#talon.DS]))
        return s
    else
        return talon.description
    end
end
function ColorText2(s)
    s = "|cffffcc00" .. s .. "|r"
    return s
end

function DestroyTalonFH()
    for i = 1, #TableTalonsFH do
        BlzDestroyFrame(TableTalonsFH[i])
    end
    TableTalonsFH={}
    TalonInSlot={}
end