---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 26.10.2024 9:31
---
function InvulRandomUnitsCountTimed(pid,k,timed)
    local units=FindRandomUnitsMax(pid,k)
    for i=1,#units do
        SetUnitInvulnerable(units[i],true)
        local eff=AddSpecialEffectTarget("Abilities\\Spells\\Human\\DivineShield\\DivineShieldTarget.mdl",units[i],"origin")
        TimerStart(CreateTimer(), timed, false, function()
            SetUnitInvulnerable(units[i],false)
            DestroyEffect(eff)
        end)
    end
end