---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 26.10.2024 10:33
---
function SummonCountUnitTypeForUnitPositionForPid(k,id,posUnit,pid)
    for i=1,k do
        local new=CreateUnit(Player(pid),id,GetUnitX(posUnit),GetUnitY(posUnit),GetRandomReal(0,360))
        IssueImmediateOrder(new,"stop")
        DestroyEffect(AddSpecialEffect("Abilities\\Spells\\Human\\MassTeleport\\MassTeleportCaster.mdl", GetUnitXY(new)))
    end
end