---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 26.10.2024 13:13
---
function CreateFrameBonusTimed(pid,amount,state)
    local timed=2
    local speed=0.0002
    local dist=0.01
    local x,y=0.62,0.57
    if not BonusSource then
        BonusSource = BlzCreateFrameByType("BACKDROP", "Face", BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), "", 0)
    end
    BlzFrameSetParent(BonusSource, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    local h = BlzCreateFrameByType("TEXT", "ButtonChargesText", BonusSource, "", 0)
    BlzFrameSetScale(h, 1.2)
    BlzFrameSetAbsPoint(h, FRAMEPOINT_RIGHT,x,y)
    BlzFrameSetText(h, "+"..GetRandomInt(0,999))
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        timed=timed-TIMER_PERIOD64
        if timed<=0 then
            BlzDestroyFrame(h)
        else
            if dist>0 then
                BlzFrameSetAbsPoint(h, FRAMEPOINT_RIGHT,x, y)
                y=y-speed
                dist=dist-speed
            end
        end
    end)
end

function CreateFlyFrame(data, parent, textTip)
    --print("где подсказка?")
    local text = BlzCreateFrameByType("TEXT", "ButtonChargesText", parent, "", 0)
    local y=0.005
    BlzFrameSetParent(text, BlzGetFrameByName("ConsoleUIBackdrop", 0))
    BlzFrameSetText(text, textTip)
    BlzFrameSetScale(text, 1.4)
    BlzFrameSetPoint(text, FRAMEPOINT_TOP, parent, FRAMEPOINT_TOP, 0.00, y)
    BlzFrameSetTextColor(text, BlzConvertColor(255, 140, 140, 255))
    if data.ShowDownPanel then
        BlzFrameSetVisible(text,GetLocalPlayer() == Player(data.pid))
    else
        BlzFrameSetVisible(text,false)
    end
    local a=0
    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        a=a+10
        --print(a)
        BlzFrameSetAlpha(text,a)
        if a>=250 then
            -- print("revers")
            --BlzDestroyFrame(text)
            TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
                a=a-5
                BlzFrameSetAlpha(text,a)
                -- print(a)
                if a<=0 then
                    --print("destroy",y)
                    DestroyTimer(GetExpiredTimer())
                    BlzDestroyFrame(text)
                end
            end)
            DestroyTimer(GetExpiredTimer())
        end
    end)

    TimerStart(CreateTimer(), TIMER_PERIOD64, true, function()
        y=y+0.0005
        BlzFrameSetPoint(text, FRAMEPOINT_TOP, parent, FRAMEPOINT_TOP, 0.00, y)
        if y>0.2 then
            DestroyTimer(GetExpiredTimer())
        end
        --print(y)
    end)
end